destination_dir=/opt/Xilinx

# Import tool preferences from previous version
copy_preferences=N

# Use multiple CPU cores for faster installation
use_multiple_cores=Y

application=Acquire or Manage a License Key::0

################################################################
# ISE WebPACK Config Template
################################################################

package=ISE WebPACK::1
application=setupEnv.sh::0
application=Install Linux System Generator Info XML::0
application=Ensure Linux System Generator Symlinks::0
application=Install Cable Drivers::0
