#### Vivado HL WebPACK Install Configuration ####
Edition=Vivado HL WebPACK
#Product=Vivado
Destination=/opt/Xilinx
Modules=Vivado:1,Artix-7:1,Kintex-7:0,Zynq-7000:0,Software Development Kit (SDK):0,DocNav:0,System Generator for DSP:0
#InstallOptions=Acquire or Manage a License Key:0,Enable WebTalk for Vivado to send usage statistics to Xilinx:0
CreateProgramGroupShortcuts=0
ProgramGroupFolder=Xilinx Design Tools
CreateShortcutsForAllUsers=0
CreateDesktopShortcuts=0
CreateFileAssociation=0
