services:
  ise:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ISE_VERSION=${ISE_VERSION}
      additional_contexts:
        - installer_dir=${INSTALLER_DIR}
        - config_dir=${CONFIG_DIR}
    image: ise:${ISE_VERSION}
