services:
  vivado:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VIVADO_VERSION=${VIVADO_VERSION}
      additional_contexts:
        - installer_dir=${INSTALLER_DIR}
        - config_dir=${CONFIG_DIR}
    image: vivado:${VIVADO_VERSION}
