# Common settings shared between containers
x-vivado-runtime: &vivado-runtime
  image: vivado:${VIVADO_VERSION}
  environment:
    - LD_PRELOAD=/usr/local/lib/flock_shim.so  # spoof flock() on non-POSIX filesystems

services:
  # shim-builder:
  #   build:
  #     context: ../c
  #     dockerfile: Dockerfile.builder
  #   volumes:
  #     - ../c:/build/c
  #     - ../lib:/build/lib
  #   working_dir: /build/c

  web-display:
    build:
      context: ../novnc-display
      dockerfile: Dockerfile.novnc
    image: web-display:latest
    ports:
      - "6080:6080"
    volumes:
      - x11-socket:/tmp/.X11-unix

  vivado:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VIVADO_VERSION=${VIVADO_VERSION}
      additional_contexts:
        - installer_dir=${INSTALLER_DIR}
        - config_dir=${CONFIG_DIR}
    image: vivado:${VIVADO_VERSION}

  vivado-webapp:
    <<: *vivado-runtime
    pid: "service:web-display"
    environment:
      - LD_PRELOAD=/usr/local/lib/flock_shim.so
      - DISPLAY=:0
      - XAUTHORITY=/home/guest/.Xauthority
    volumes:
      - x11-socket:/tmp/.X11-unix
      - ${XAUTHORITY:-${HOME}/.Xauthority}:/home/guest/.Xauthority
      - ${WORKSPACE}:/home/guest/workspace
      - ../c/lib/flock_shim_64.so:/usr/local/lib/flock_shim.so:ro
    depends_on:
      - web-display
      - vivado
      - shim-builder
    command: >
      /bin/bash -c "sleep 5 &&
      source /opt/Xilinx/Vivado/${VIVADO_VERSION}/settings64.sh &&
      vivado -log /home/guest/.vivado -jou /home/guest/.vivado;
      kill -15 1"

  vivado-linux:
    <<: *vivado-runtime
    depends_on:
      - shim-builder
    environment:
      - LD_PRELOAD=/usr/local/lib/flock_shim.so
      - DISPLAY=$DISPLAY
      - XAUTHORITY=/home/guest/.Xauthority
      - _JAVA_AWT_WM_NONREPARENTING=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY:-${HOME}/.Xauthority}:/home/guest/.Xauthority
      - ${WORKSPACE}:/home/guest/workspace
      - ../c/lib/flock_shim_64.so:/usr/local/lib/flock_shim.so:ro
    command: >
      /bin/bash -c "source /opt/Xilinx/Vivado/${VIVADO_VERSION}/settings64.sh
      && vivado -log /home/guest/.vivado -jou /home/guest/.vivado"

volumes:
  x11-socket:
